import type { NewsDocument, NewsEvent } from '../../../agents/news/types.ts';
import type { NewsDataSnapshot } from '../../types.ts';
import { deduplicate, publishedAt } from './validator.ts';
type Feed = { title?: unknown; summary?: unknown; time_published?: unknown; source?: unknown; url?: unknown; overall_sentiment_label?: unknown; relevance_score?: unknown; ticker_sentiment?: unknown };
export function mapAlphaVantageNews(payload: { feed?: unknown }, retrievedAt: string, analysisTime: string, symbol = 'UNKNOWN'): NewsDataSnapshot {
  if (!Array.isArray(payload.feed)) throw new Error('INVALID_NEWS_PAYLOAD');
  const docs: NewsDocument[] = payload.feed.slice(0, 20).map((item, index) => { const feed = item as Feed; const time = publishedAt(feed.time_published); if (time > analysisTime) throw new Error('LOOK_AHEAD_BLOCKED'); if (typeof feed.title !== 'string' || typeof feed.source !== 'string' || typeof feed.url !== 'string') throw new Error('INVALID_NEWS_DOCUMENT'); const sentiment = typeof feed.overall_sentiment_label === 'string' ? feed.overall_sentiment_label : 'Neutral'; const relevance = typeof feed.relevance_score === 'string' ? Number(feed.relevance_score) : null; return { id: `alpha-vantage-news:${index}:${feed.url}`, sourceId: 'alpha-vantage', sourceName: feed.source, sourceTier: 'B', title: feed.title, summary: typeof feed.summary === 'string' ? feed.summary : undefined, publishedAt: time, retrievedAt, language: 'en', country: 'US', categories: ['market-news'], affectedAssets: [{ symbol, assetType: 'STOCK', relation: 'DIRECT' }], facts: [], metadata: { url: feed.url, sentiment, importance: relevance !== null && relevance >= .5 ? 'HIGH' : 'MEDIUM' } }; });
  const documents = deduplicate(docs); const events: NewsEvent[] = documents.filter((document) => !document.duplicateGroupId).map((primaryDocument) => ({ eventId: primaryDocument.id, primaryDocument, relatedDocuments: documents.filter((document) => document.duplicateGroupId === primaryDocument.duplicateGroupId) })); return { documents, events };
}
