import { strict as assert } from 'node:assert';
import { createStockFundamentalContext } from '../../../stock-analysis/fundamental/fundamental-context-engine.ts';
import { FundamentalCacheService, fundamentalSnapshotFromRow } from '../fundamental-cache-service.ts';
import type { FundamentalDataSnapshot } from '../../types.ts';

const at = '2026-08-20T12:00:00.000Z';
const asset = { id: 'asset-nvda', symbol: 'NVDA', name: 'NVIDIA Corporation', market: 'NASDAQ', country: 'US', currency: 'USD', timezone: 'America/New_York', identifiers: [] } as const;
const snapshot = (symbol = 'NVDA'): FundamentalDataSnapshot => ({ metrics: { revenueGrowth: .25, operatingMargin: .5, netMargin: .4, roe: 1.1, operatingCashFlow: 100, freeCashFlow: 80, cash: 40, totalDebt: 20, debtToEquity: .2, netDebt: -20, pe: 30, pb: 20, evEbitda: 25 }, snapshot: { asset: { symbol, name: symbol, currency: 'USD' }, asOfTime: '2026-08-15T00:00:00.000Z', reportingPeriod: { periodEnd: '2026-08-15' }, financials: {}, growth: {}, profitability: {}, balanceSheet: {}, cashFlow: {}, valuation: {}, quality: { coverage: .8, confidence: .8, status: 'COMPLETE' }, evidence: [{ id: 'fundamental', type: 'CALCULATION', label: 'fixture' }], sourceStatus: 'READY', direction: 'UNKNOWN' } });
class MemoryRepository {
  rows: Record<string, unknown>[] = [];
  async findLatestUsableSnapshot(input: { assetId: string; sourceId: string; analysisTime: string }) { return this.rows.filter(row => row.asset_id === input.assetId && row.source_id === input.sourceId && String(row.data_as_of) <= input.analysisTime).sort((a, b) => String(b.data_as_of).localeCompare(String(a.data_as_of)) || String(b.retrieved_at).localeCompare(String(a.retrieved_at)))[0] ?? null; }
  async insert(assetId: string, sourceId: string, data: FundamentalDataSnapshot, retrievedAt: string) { const exists = this.rows.find(row => row.asset_id === assetId && row.source_id === sourceId && row.data_as_of === data.snapshot.asOfTime && row.fiscal_period === data.snapshot.reportingPeriod.periodEnd); if (exists) return { action: 'SKIPPED' as const, id: String(exists.id) }; const m = data.metrics; const row = { id: String(this.rows.length + 1), asset_id: assetId, source_id: sourceId, fiscal_period: data.snapshot.reportingPeriod.periodEnd, period_end: data.snapshot.reportingPeriod.periodEnd, data_as_of: data.snapshot.asOfTime, retrieved_at: retrievedAt, revenue_growth: m.revenueGrowth, operating_income_growth: m.operatingIncomeGrowth ?? null, net_income_growth: m.netIncomeGrowth ?? null, eps_growth: m.epsGrowth ?? null, operating_margin: m.operatingMargin, net_margin: m.netMargin, roe: m.roe, operating_cash_flow: m.operatingCashFlow, free_cash_flow: m.freeCashFlow, free_cash_flow_margin: m.freeCashFlowMargin ?? null, cash: m.cash, total_debt: m.totalDebt, debt_to_equity: m.debtToEquity, net_debt: m.netDebt, pe: m.pe, pb: m.pb, ev_ebitda: m.evEbitda, data_quality: data.snapshot.quality.status, confidence: data.snapshot.quality.confidence, evidence: structuredClone(data.snapshot.evidence) }; this.rows.push(row); return { action: 'INSERTED' as const, id: row.id }; }
}
class FixtureProvider { calls = 0; constructor(private readonly data: FundamentalDataSnapshot | null) {} async getFundamentalData() { this.calls++; return this.data ? { data: structuredClone(this.data), source: 'fixture', status: 'READY' as const, freshness: { retrievedAt: at, dataAsOfTime: this.data.snapshot.asOfTime, staleAfter: null, freshnessStatus: 'FRESH' as const }, errors: [] } : { data: null, source: 'fixture', status: 'FAILED' as const, freshness: { retrievedAt: at, dataAsOfTime: null, staleAfter: null, freshnessStatus: 'UNKNOWN' as const }, errors: [{ source: 'fixture', code: 'DOWN', message: 'down', retryable: true }] }; } }
const registration = { ensureAlphaVantage: async () => ({ id: 'alpha', code: 'ALPHA_VANTAGE' }) };
const service = (provider: FixtureProvider, repo: MemoryRepository) => new FundamentalCacheService(provider as never, repo as never, registration);

async function main() {
  const repo = new MemoryRepository(); const provider = new FixtureProvider(snapshot()); const cache = service(provider, repo);
  assert.equal((await cache.get(asset, at)).cacheStatus, 'MISS'); assert.equal(repo.rows.length, 1); assert.equal(provider.calls, 1);
  const warm = await cache.get(asset, at); assert.equal(warm.cacheStatus, 'HIT'); assert.equal(warm.providerCalls, 0); assert.equal(provider.calls, 1); assert.equal(repo.rows.length, 1);
  const direct = snapshot(); const restored = fundamentalSnapshotFromRow(repo.rows[0]!, asset); assert.deepEqual(createStockFundamentalContext(restored), createStockFundamentalContext(direct), 'M5-E cold and DB round-trip agree');
  await repo.insert(asset.id, 'alpha', direct, at); assert.equal(repo.rows.length, 1, 'idempotent normalized snapshot');
  const staleRepo = new MemoryRepository(); await staleRepo.insert(asset.id, 'alpha', snapshot(), '2026-08-19T00:00:00.000Z'); staleRepo.rows[0]!.retrieved_at = '2026-08-19T00:00:00.000Z'; assert.equal((await service(new FixtureProvider(snapshot()), staleRepo).get(asset, at)).cacheStatus, 'REFRESHED');
  const fallbackRepo = new MemoryRepository(); await fallbackRepo.insert(asset.id, 'alpha', snapshot(), '2026-08-19T00:00:00.000Z'); fallbackRepo.rows[0]!.retrieved_at = '2026-08-19T00:00:00.000Z'; assert.equal((await service(new FixtureProvider(null), fallbackRepo).get(asset, at)).cacheStatus, 'STALE_FALLBACK');
  const expiredRepo = new MemoryRepository(); await expiredRepo.insert(asset.id, 'alpha', snapshot(), '2026-01-01T00:00:00.000Z'); expiredRepo.rows[0]!.retrieved_at = '2026-01-01T00:00:00.000Z'; assert.equal((await service(new FixtureProvider(null), expiredRepo).get(asset, at)).cacheStatus, 'EXPIRED');
  assert.equal((await service(new FixtureProvider(null), new MemoryRepository()).get(asset, at)).cacheStatus, 'UNAVAILABLE');
  const quotaProvider = { async getFundamentalData() { return { data: null, source: 'fixture', status: 'FAILED' as const, freshness: { retrievedAt: at, dataAsOfTime: null, staleAfter: null, freshnessStatus: 'UNKNOWN' as const }, errors: [{ source: 'fixture', code: 'PROVIDER_QUOTA', message: 'quota', retryable: false }] }; } };
  const quota = await service(quotaProvider as never, new MemoryRepository()).envelope(asset, at); assert.equal(quota.errors[0]?.code, 'PROVIDER_QUOTA', 'quota error code is preserved');
  const futureRepo = new MemoryRepository(); await futureRepo.insert(asset.id, 'alpha', snapshot(), at); futureRepo.rows[0]!.data_as_of = '2026-08-21T00:00:00.000Z'; assert.equal((await service(new FixtureProvider(null), futureRepo).get(asset, at)).cacheStatus, 'UNAVAILABLE', 'repository look-ahead filter is preserved');
  console.log('Fundamental cache QA PASS: cold/warm/provider-count/idempotency/round-trip/stale/fallback/expired/miss-failure/look-ahead/M5-E');
}
main();
