import { strict as assert } from 'node:assert';
import { resolveUsEquity, type StockSearchResult } from '../stock-asset-resolver.ts';
const canonical = (symbol: string) => ({ id: `asset-${symbol}`, symbol, name: symbol, assetType: 'STOCK', exchange: 'NASDAQ', country: 'US', currency: 'USD', timezone: 'America/New_York', isActive: true });
const provider = (symbol: string, calls: { value: number }) => async (): Promise<readonly StockSearchResult[]> => { calls.value++; return [{ symbol, name: symbol, exchange: 'NASDAQ', country: 'US', currency: 'USD', type: 'Common Stock', providerIdentifier: symbol }]; };
for (const symbol of ['NVDA', 'AAPL']) { const calls = { value: 0 }; const result = await resolveUsEquity(symbol, { canonical: { resolveUs: async () => canonical(symbol) }, search: provider(symbol, calls) }); assert.equal(result?.asset.id, `asset-${symbol}`); assert.equal(calls.value, 0); }
{ const calls = { value: 0 }, rows = new Map<string, any>(); const db = { resolveUs: async (symbol: string) => rows.get(symbol) ?? null, registerUs: async (input: any) => { const row = canonical(input.symbol); rows.set(input.symbol, row); return row; } }; assert.equal((await resolveUsEquity('TTWO', { canonical: db, search: provider('TTWO', calls) }))?.asset.symbol, 'TTWO'); assert.equal(calls.value, 1); assert.equal((await resolveUsEquity('TTWO', { canonical: db, search: provider('TTWO', calls) }))?.asset.symbol, 'TTWO'); assert.equal(calls.value, 1); }
{ const calls = { value: 0 }, row = canonical('TSLA'); assert.equal((await resolveUsEquity('TSLA', { canonical: { resolveUs: async () => { throw Error('db'); }, registerUs: async () => { throw Error('duplicate'); } }, search: provider('TSLA', calls) })), null); assert.equal(calls.value, 1); void row; }
assert.equal(await resolveUsEquity('BTC', { canonical: { resolveUs: async () => null }, search: async () => [] }), null);
console.log('Canonical US resolver QA PASS: NVDA/AAPL hit, miss, DB error fallback, unsupported, provider counts');
