import { StockLiveDataOrchestrator } from '../stock-live-data-orchestrator.ts';
import type { LiveDataProviders } from '../provider-contracts.ts';
import type { SourceEnvelope } from '../types.ts';
import type { AssetRecord } from '../../stock-analysis/types.ts';

const at = '2026-08-25T00:00:00.000Z'; const earlier = '2026-08-24T00:00:00.000Z';
function assert(value: unknown, message: string): asserts value { if (!value) throw new Error(message); }
const ready = <T>(data: T, source: string, dataAsOfTime = at): SourceEnvelope<T> => ({ data, source, status: 'READY', freshness: { retrievedAt: at, dataAsOfTime, staleAfter: '2026-08-26T00:00:00.000Z', freshnessStatus: 'UNKNOWN' }, errors: [] });
const asset = (symbol = 'NVDA', market = 'NASDAQ', country = 'US'): AssetRecord => ({ id: `asset-${symbol}`, symbol, name: symbol, assetType: 'STOCK', exchange: market, country, currency: country === 'KR' ? 'KRW' : 'USD', timezone: 'UTC', isActive: true });
const prices = Array.from({ length: 130 }, (_, index) => ({ timestamp: new Date(Date.UTC(2026, 3, 17 + index)).toISOString(), open: 100 + index, high: 101 + index, low: 99 + index, close: 100 + index, volume: 1000 + index }));
const market = () => ready({ ohlcv: prices.filter((point) => point.timestamp <= at), currency: 'USD', timezone: 'UTC', adjustment: 'ADJUSTED' as const }, 'fixture-market');
const fundamental = () => ready({ snapshot: { asset: { symbol: 'NVDA', name: 'NVIDIA', currency: 'USD' }, asOfTime: earlier, reportingPeriod: { periodEnd: earlier }, financials: {}, growth: {}, profitability: {}, balanceSheet: {}, cashFlow: {}, quality: { coverage: 1, confidence: 1, status: 'COMPLETE' as const }, evidence: [], sourceStatus: 'READY', direction: 'POSITIVE' as const }, metrics: { revenueGrowth: .2, operatingIncomeGrowth: .2, netIncomeGrowth: .2, epsGrowth: .2, operatingMargin: .4, roe: .5, operatingCashFlow: 1, freeCashFlow: 1, debtToEquity: .1, netDebt: -1, cash: 2 } }, 'fixture-fundamental', earlier);
const industry = () => ready({ context: { industry: 'Semiconductor', sector: 'Technology', demand: { state: 'ACCELERATING' as const, evidence: [] }, supply: { state: 'TIGHT' as const, evidence: [] }, pricing: { state: 'RISING' as const, evidence: [] }, inventory: { state: 'DRAWING' as const, evidence: [] }, capacity: { state: 'TIGHT' as const, evidence: [] }, asOfTime: earlier } }, 'fixture-industry', earlier);
const providers = (overrides: Partial<LiveDataProviders> = {}): LiveDataProviders => ({ market: { id: 'market', getMarketData: async () => market() }, fundamental: { id: 'fundamental', getFundamentalData: async () => fundamental() }, industry: { id: 'industry', getIndustryData: async () => industry() }, news: { id: 'news', getNewsData: async () => ready({ documents: [], events: [] }, 'fixture-news') }, research: { id: 'research', getResearchData: async () => ready({ documents: [] }, 'fixture-research') }, ...overrides });
const run = (overrides: Partial<LiveDataProviders> = {}, stock = asset()) => new StockLiveDataOrchestrator().run({ asset: stock, identifiers: [{ assetId: stock.id, identifierType: 'TICKER', identifierValue: stock.symbol!, isActive: true }], analysisTime: at, from: '2026-01-01T00:00:00.000Z', to: at, providers: providers(overrides) });

const all = await run(); assert(all.snapshot.coverage.available === 5 && all.pipeline.technical.status !== 'UNKNOWN', 'A all live provider sources assemble full technical context');
const marketOnly = await run({ fundamental: undefined, industry: undefined, news: undefined, research: undefined }); assert(marketOnly.pipeline.technical.status !== 'UNKNOWN' && marketOnly.snapshot.fundamentalData.status === 'UNAVAILABLE', 'B market-only keeps technical and marks other sources unavailable');
const fundamentalFailure = await run({ fundamental: { id: 'broken', getFundamentalData: async () => { throw new Error('offline'); } } }); assert(fundamentalFailure.snapshot.fundamentalData.status === 'FAILED' && fundamentalFailure.pipeline.technical.status !== 'UNKNOWN', 'C fundamental failure does not stop remaining sources');
const newsFailure = await run({ news: { id: 'broken', getNewsData: async () => { throw new Error('offline'); } } }); assert(newsFailure.snapshot.newsData.status === 'FAILED' && newsFailure.snapshot.marketData.status === 'READY', 'D news failure does not stop remaining sources');
const stale = await run({ market: { id: 'stale', getMarketData: async () => ({ ...market(), freshness: { retrievedAt: earlier, dataAsOfTime: earlier, staleAfter: '2026-08-24T00:00:00.000Z', freshnessStatus: 'UNKNOWN' } }) } }); assert(stale.snapshot.marketData.freshness.freshnessStatus === 'STALE', 'E stale market data is labeled stale');
const future = await run({ market: { id: 'future', getMarketData: async () => ready({ ohlcv: [...prices.filter((point) => point.timestamp <= at), { ...prices[0], timestamp: '2026-08-26T00:00:00.000Z' }], currency: 'USD', timezone: 'UTC', adjustment: 'ADJUSTED' }, 'future') } }); assert(future.snapshot.marketData.status === 'FAILED' && future.snapshot.errors.some((error) => error.code === 'LOOK_AHEAD_BLOCKED'), 'F future timestamp is blocked');
const korea = await run({}, asset('005930', 'KRX', 'KR')); assert(korea.marketRoute === 'KOREA', 'G Korea asset uses Korea route');
const us = await run(); assert(us.marketRoute === 'GLOBAL', 'H US asset uses Global route');
try { await run({}, { ...asset(), assetType: 'ETF' }); throw new Error('unsupported asset accepted'); } catch (error) { assert(String(error).includes('Unsupported asset'), 'I unsupported asset returns a clear error'); }
const immutableInput = providers(); const before = JSON.stringify(immutableInput); const one = await run(); const two = await run(); assert(JSON.stringify(immutableInput) === before, 'J provider input remains immutable'); assert(JSON.stringify(one.snapshot) === JSON.stringify(two.snapshot), 'K identical fixtures are deterministic');
console.log('M5-J live data orchestration QA PASS');
