import { IngestionError } from '../errors.ts';
import { normalizeEconomicObservation } from '../normalizers/economic-observation.ts';
import { normalizeMarketPrice } from '../normalizers/market-price.ts';
import { FixtureProvider, type FixtureEconomicRaw, type FixtureMarketRaw } from '../providers/fixture-provider.ts';
import { runBatchIngestion } from '../run-batch-ingestion.ts';
import type { IngestionProvider } from '../providers/types.ts';
import type { IngestionWriter, NormalizedEconomicObservation, NormalizedMarketPrice, WriteResult } from '../types.ts';
import { validateEconomicObservation, validateMarketPrice } from '../validators.ts';

class MemoryMarketWriter implements IngestionWriter<NormalizedMarketPrice> { rows = new Map<string, NormalizedMarketPrice>(); calls = 0; async write(row: NormalizedMarketPrice): Promise<WriteResult> { this.calls += 1; const key = `${row.assetId}/${row.sourceId}/${row.interval}/${row.marketTime}`; const current = this.rows.get(key); if (current && JSON.stringify(current) === JSON.stringify(row)) return { action: 'skipped' }; this.rows.set(key, row); return { action: current ? 'updated' : 'inserted' }; } }
class MemoryEconomicWriter implements IngestionWriter<NormalizedEconomicObservation> { rows = new Map<string, NormalizedEconomicObservation>(); async write(row: NormalizedEconomicObservation): Promise<WriteResult> { const key = `${row.seriesId}/${row.observationDate}/${row.vintageAt}`; if (this.rows.has(key)) return { action: 'skipped' }; this.rows.set(key, row); return { action: 'inserted' }; } }
class FailingProvider implements IngestionProvider<void, FixtureMarketRaw[]> { readonly code = 'QA_FAILING_PROVIDER'; async fetch(): Promise<FixtureMarketRaw[]> { throw new IngestionError('PROVIDER_ERROR', 'fixture timeout', {}, true); } }
class FailOnceWriter implements IngestionWriter<NormalizedMarketPrice> { calls = 0; async write(row: NormalizedMarketPrice): Promise<WriteResult> { this.calls += 1; if (row.marketTime === '2026-01-04T00:00:00Z') throw new IngestionError('DATABASE_ERROR', 'temporary fixture database error', {}, true); return { action: 'inserted' }; } }
const assetId = '11111111-1111-4111-8111-111111111111'; const sourceId = '22222222-2222-4222-8222-222222222222'; const seriesId = '33333333-3333-4333-8333-333333333333';
const market = (time: string, close: string): FixtureMarketRaw => ({ assetId, sourceId, interval: '1d', marketTime: time, close, currency: 'USD', retrievedAt: '2026-01-05T00:00:00Z' });
const economic = (vintageAt: string, value?: string, valueText?: string): FixtureEconomicRaw => ({ seriesId, observationDate: '2026-01-01', vintageAt, value, valueText, retrievedAt: '2026-01-05T00:00:00Z', metadata: { fixture: true } });
async function main() {
  const writer = new MemoryMarketWriter(); const marketRows = [market('2026-01-02T00:00:00Z', '100'), market('2026-01-03T00:00:00Z', '200'), market('2026-01-02T00:00:00Z', '101'), market('2026-01-04T00:00:00Z', '-1'), market('2026-01-03T00:00:00Z', '200')];
  const dry = await runBatchIngestion({ provider: new FixtureProvider<void, FixtureMarketRaw[]>(marketRows), input: undefined, normalize: normalizeMarketPrice, validate: validateMarketPrice, writer, dryRun: true }); if (writer.calls !== 0 || dry.valid !== 4 || dry.rejected !== 1) throw new Error('dry run batch failed');
  const marketSummary = await runBatchIngestion({ provider: new FixtureProvider<void, FixtureMarketRaw[]>(marketRows), input: undefined, normalize: normalizeMarketPrice, validate: validateMarketPrice, writer }); if (marketSummary.inserted !== 2 || marketSummary.updated !== 1 || marketSummary.skipped !== 1 || marketSummary.rejected !== 1 || marketSummary.failed !== 0) throw new Error('market batch failed');
  const econWriter = new MemoryEconomicWriter(); const economicSummary = await runBatchIngestion({ provider: new FixtureProvider<void, FixtureEconomicRaw[]>([economic('2026-01-03T00:00:00Z', '100'), economic('2026-01-03T00:00:00Z', '100'), economic('2026-01-04T00:00:00Z', '105'), economic('2026-01-05T00:00:00Z', undefined, 'MISSING'), economic('2026-01-06T00:00:00Z')]), input: undefined, normalize: normalizeEconomicObservation, validate: validateEconomicObservation, writer: econWriter }); if (economicSummary.inserted !== 3 || economicSummary.skipped !== 1 || economicSummary.rejected !== 1) throw new Error('economic batch failed');
  const partial = await runBatchIngestion({ provider: new FixtureProvider<void, FixtureMarketRaw[]>([market('2026-01-04T00:00:00Z', '1'), market('2026-01-05T00:00:00Z', '2')]), input: undefined, normalize: normalizeMarketPrice, validate: validateMarketPrice, writer: new FailOnceWriter() }); if (partial.failed !== 1 || partial.inserted !== 1 || !partial.errors[0].retryable) throw new Error('partial database failure failed');
  const providerFailure = await runBatchIngestion({ provider: new FailingProvider(), input: undefined, normalize: normalizeMarketPrice, validate: validateMarketPrice, writer }); if (!providerFailure.runFailed || providerFailure.failed !== 1 || !providerFailure.errors[0].retryable) throw new Error('provider failure failed');
  const normalization = await runBatchIngestion({ provider: new FixtureProvider<void, FixtureMarketRaw[]>([market('invalid-date', '1'), market('2026-01-06T00:00:00Z', '2')]), input: undefined, normalize: (raw) => { if (raw.marketTime === 'invalid-date') throw new Error('fixture normalization failure'); return normalizeMarketPrice(raw); }, validate: validateMarketPrice, writer: new MemoryMarketWriter() }); if (normalization.failed !== 1 || normalization.inserted !== 1 || normalization.errors[0].retryable) throw new Error('normalization isolation failed');
  console.log('M1-G fixture batch QA PASS');
}
main();
