import { stockFundamentalConfig as config } from './config.ts';
import type { BalanceSheetState, CashFlowState, EarningsQualityState, FundamentalMetrics, GrowthState, ProfitabilityState, StockFundamentalContext, StockFundamentalInput, ValuationState } from './types.ts';

const valid = (value: number | null | undefined): value is number => typeof value === 'number' && Number.isFinite(value);
const growthValues = (m: FundamentalMetrics) => [m.revenueGrowth, m.operatingIncomeGrowth, m.netIncomeGrowth, m.epsGrowth].filter(valid);
function growth(m: FundamentalMetrics): GrowthState { const values = growthValues(m); if (values.length < 2) return 'UNKNOWN'; if (values.every((x) => x >= config.growth.strong)) return 'STRONG'; if (values.every((x) => x <= 0)) return values.every((x) => x < 0) ? 'WEAK' : 'WEAKENING'; if (values.every((x) => x >= 0) && values.some((x) => x >= config.growth.improving)) return 'IMPROVING'; return 'STABLE'; }
function profitability(m: FundamentalMetrics): ProfitabilityState { const margin = m.operatingMargin, roe = m.roe; if (!valid(margin) || !valid(roe)) return 'UNKNOWN'; const previous = m.previous; const deteriorating = previous && [[margin, previous.operatingMargin], [m.netMargin, previous.netMargin], [roe, previous.roe]].filter(([now, before]) => valid(now) && valid(before) && now < before - config.profitability.deterioration).length >= 2; if (deteriorating) return 'DETERIORATING'; if (margin >= config.profitability.strongMargin && roe >= config.profitability.strongRoe) return 'STRONG'; if (margin >= config.profitability.healthyMargin && roe >= config.profitability.healthyRoe) return 'HEALTHY'; if (margin < config.profitability.weak || roe < config.profitability.weak) return 'WEAK'; return 'NORMAL'; }
function cashFlow(m: FundamentalMetrics): CashFlowState { if (!valid(m.operatingCashFlow) || !valid(m.freeCashFlow)) return 'UNKNOWN'; if (m.operatingCashFlow < 0 || m.freeCashFlow < 0) return 'NEGATIVE'; if (valid(m.freeCashFlowMargin) && m.freeCashFlowMargin >= config.cashFlow.strongMargin) return 'STRONG'; return m.freeCashFlow > 0 ? 'HEALTHY' : 'WEAK'; }
function balanceSheet(m: FundamentalMetrics): BalanceSheetState { if (!valid(m.debtToEquity) || !valid(m.netDebt) || !valid(m.cash)) return 'UNKNOWN'; if (m.debtToEquity >= config.balanceSheet.stressedDebtToEquity) return 'STRESSED'; if (m.debtToEquity >= config.balanceSheet.leveragedDebtToEquity || m.netDebt > m.cash) return 'LEVERAGED'; if (m.debtToEquity <= config.balanceSheet.strongDebtToEquity && m.netDebt <= 0) return 'STRONG'; if (m.debtToEquity <= config.balanceSheet.healthyDebtToEquity) return 'HEALTHY'; return 'NORMAL'; }
function valuation(m: FundamentalMetrics, benchmark: StockFundamentalInput['benchmark']): ValuationState { if (!benchmark) return 'UNKNOWN'; const pairs = [[m.pe, benchmark.pe], [m.pb, benchmark.pb], [m.evEbitda, benchmark.evEbitda]].filter((pair): pair is [number, number] => valid(pair[0]) && valid(pair[1]) && pair[0] > 0 && pair[1] > 0); if (!pairs.length) return 'UNKNOWN'; const ratios = pairs.map(([actual, reference]) => actual / reference); if (ratios.every((ratio) => ratio >= 1 + config.valuation.band)) return 'EXPENSIVE'; if (ratios.every((ratio) => ratio <= 1 - config.valuation.band)) return 'CHEAP'; return 'FAIR'; }
function earningsQuality(m: FundamentalMetrics, cash: CashFlowState): EarningsQualityState { const profitGrowth = [m.operatingIncomeGrowth, m.netIncomeGrowth, m.epsGrowth].filter(valid); if (!profitGrowth.length || cash === 'UNKNOWN') return 'UNKNOWN'; if (profitGrowth.some((value) => value > 0) && (cash === 'WEAK' || cash === 'NEGATIVE')) return 'LOW'; if (profitGrowth.every((value) => value >= 0) && (cash === 'STRONG' || cash === 'HEALTHY')) return cash === 'STRONG' ? 'HIGH' : 'NORMAL'; return 'NORMAL'; }
/** Reads supplied snapshot/metrics only; no provider, peer, estimate, or historical fact is created. */
export function createStockFundamentalContext(input: StockFundamentalInput): StockFundamentalContext {
  const m = input.metrics, growthState = growth(m), profitabilityState = profitability(m), cashFlowState = cashFlow(m), balanceSheetState = balanceSheet(m), valuationState = valuation(m, input.benchmark), earningsQualityState = earningsQuality(m, cashFlowState);
  const domains = [growthState, profitabilityState, cashFlowState, balanceSheetState, valuationState, earningsQualityState]; const known = domains.filter((state) => state !== 'UNKNOWN').length;
  const unknowns = [['growth', growthState], ['profitability', profitabilityState], ['cash flow', cashFlowState], ['balance sheet', balanceSheetState], ['valuation', valuationState], ['earnings quality', earningsQualityState]].filter(([, state]) => state === 'UNKNOWN').map(([name]) => `${name} inputs are insufficient`);
  return { growthState, profitabilityState, cashFlowState, balanceSheetState, valuationState, earningsQualityState, confidence: known === 0 ? null : known / domains.length, evidence: [...input.snapshot.evidence], unknowns, asOfTime: input.snapshot.asOfTime, configVersion: config.version };
}
