BEGIN;
ALTER TABLE analysis_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE cio_decisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE cio_scenarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE decision_invalidation_conditions ENABLE ROW LEVEL SECURITY;
ALTER TABLE decision_monitoring_priorities ENABLE ROW LEVEL SECURITY;
COMMIT;
