BEGIN;

CREATE TABLE system_sources (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  source_type text NOT NULL,
  category text,
  country text,
  tier text NOT NULL DEFAULT 'S',
  priority smallint NOT NULL DEFAULT 100,
  reliability smallint,
  base_url text,
  credential_env_key text,
  enabled boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT system_sources_tier_check CHECK (tier IN ('S', 'A', 'B', 'C', 'D')),
  CONSTRAINT system_sources_priority_check CHECK (priority >= 0),
  CONSTRAINT system_sources_reliability_check CHECK (reliability IS NULL OR reliability BETWEEN 0 AND 100)
);

CREATE TABLE assets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol text,
  name text NOT NULL,
  asset_type text NOT NULL,
  exchange text,
  country text,
  currency char(3),
  timezone text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT assets_asset_type_check CHECK (asset_type IN ('STOCK', 'ETF', 'INDEX', 'BOND', 'FX', 'COMMODITY', 'CRYPTO'))
);

CREATE TABLE asset_identifiers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  asset_id uuid NOT NULL,
  source_id uuid NOT NULL,
  identifier_type text NOT NULL,
  identifier_value text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT asset_identifiers_asset_id_fkey
    FOREIGN KEY (asset_id) REFERENCES assets (id) ON DELETE RESTRICT,
  CONSTRAINT asset_identifiers_source_id_fkey
    FOREIGN KEY (source_id) REFERENCES system_sources (id) ON DELETE RESTRICT,
  CONSTRAINT asset_identifiers_source_identifier_unique
    UNIQUE (source_id, identifier_type, identifier_value)
);

CREATE TABLE market_prices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_id uuid NOT NULL,
  source_id uuid NOT NULL,
  interval text NOT NULL DEFAULT '1d',
  market_time timestamptz NOT NULL,
  open numeric(20,8),
  high numeric(20,8),
  low numeric(20,8),
  close numeric(20,8),
  adjusted_close numeric(20,8),
  volume numeric(24,0),
  currency char(3),
  retrieved_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT market_prices_asset_id_fkey
    FOREIGN KEY (asset_id) REFERENCES assets (id) ON DELETE RESTRICT,
  CONSTRAINT market_prices_source_id_fkey
    FOREIGN KEY (source_id) REFERENCES system_sources (id) ON DELETE RESTRICT,
  CONSTRAINT market_prices_asset_source_interval_time_unique
    UNIQUE (asset_id, source_id, interval, market_time),
  CONSTRAINT market_prices_interval_check
    CHECK (interval IN ('1m', '5m', '15m', '1h', '1d', '1w', '1mo')),
  CONSTRAINT market_prices_open_check CHECK (open IS NULL OR open >= 0),
  CONSTRAINT market_prices_high_check CHECK (high IS NULL OR high >= 0),
  CONSTRAINT market_prices_low_check CHECK (low IS NULL OR low >= 0),
  CONSTRAINT market_prices_close_check CHECK (close IS NULL OR close >= 0),
  CONSTRAINT market_prices_adjusted_close_check CHECK (adjusted_close IS NULL OR adjusted_close >= 0),
  CONSTRAINT market_prices_volume_check CHECK (volume IS NULL OR volume >= 0),
  CONSTRAINT market_prices_has_price_check
    CHECK (open IS NOT NULL OR high IS NOT NULL OR low IS NOT NULL OR close IS NOT NULL OR adjusted_close IS NOT NULL)
);

CREATE TABLE economic_series (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_id uuid NOT NULL,
  source_series_id text NOT NULL,
  name text NOT NULL,
  country text,
  frequency text NOT NULL,
  unit text,
  seasonal_adjustment text,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT economic_series_source_id_fkey
    FOREIGN KEY (source_id) REFERENCES system_sources (id) ON DELETE RESTRICT,
  CONSTRAINT economic_series_source_series_unique
    UNIQUE (source_id, source_series_id)
);

CREATE TABLE economic_observations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_id uuid NOT NULL,
  observation_date date NOT NULL,
  value numeric(24,10),
  value_text text,
  vintage_at timestamptz NOT NULL,
  source_published_at timestamptz,
  data_as_of_time timestamptz,
  retrieved_at timestamptz NOT NULL DEFAULT now(),
  revision_label text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT economic_observations_series_id_fkey
    FOREIGN KEY (series_id) REFERENCES economic_series (id) ON DELETE RESTRICT,
  CONSTRAINT economic_observations_series_observation_vintage_unique
    UNIQUE (series_id, observation_date, vintage_at),
  CONSTRAINT economic_observations_has_value_check
    CHECK (value IS NOT NULL OR value_text IS NOT NULL)
);

CREATE INDEX market_prices_asset_market_time_idx
  ON market_prices (asset_id, market_time DESC);

CREATE INDEX market_prices_source_market_time_idx
  ON market_prices (source_id, market_time DESC);

CREATE INDEX economic_observations_series_observation_vintage_idx
  ON economic_observations (series_id, observation_date DESC, vintage_at DESC);

CREATE INDEX economic_observations_series_vintage_idx
  ON economic_observations (series_id, vintage_at DESC);

COMMIT;
