BEGIN;

ALTER TABLE system_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE asset_identifiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE market_prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE economic_series ENABLE ROW LEVEL SECURITY;
ALTER TABLE economic_observations ENABLE ROW LEVEL SECURITY;

COMMIT;
