import type { StructuredLlmClient } from '../llm/types.ts';
import type { AgentEvidence, AgentRunEnvelope } from '../types.ts';
import { macroInputPrompt, macroSystemPrompt } from './prompt.ts';
import type { M2AnalysisSnapshot, MacroAgentContext, MacroAgentOutput } from './types.ts';
import { validateMacroOutput } from './validator.ts';
const now=()=>new Date().toISOString(); const domain=(s:M2AnalysisSnapshot,name:string)=>s.domainScores.find(d=>d.domain===name);
function contextOf(s:M2AnalysisSnapshot):MacroAgentContext { const macro=s.composites.macro; const entries:AgentEvidence[]=[{id:'macro',type:'CALCULATION',label:'Macro Composite',value:macro.score},{id:'risk',type:'CALCULATION',label:'Risk Context',value:s.composites.risk.riskScore},...['rates','inflation','growth','liquidity'].map(name=>({id:name,type:'CALCULATION' as const,label:`${name} Domain Score`,value:domain(s,name)?.score??null}))]; return {sourceSnapshot:{macroScore:macro.score,ratesScore:domain(s,'rates')?.score??null,inflationScore:domain(s,'inflation')?.score??null,growthScore:domain(s,'growth')?.score??null,liquidityScore:domain(s,'liquidity')?.score??null,riskScore:s.composites.risk.riskScore,stableRegime:s.stableRegime.stableRegime},evidence:entries,divergence:s.composites.divergence,rawRegime:s.rawRegime.regime,stableRegime:s.stableRegime.stableRegime,macroStatus:macro.status,macroConfidence:macro.confidence,dataAsOfTime:s.asOfTime,configVersions:s.configVersions}; }
function unknownEnvelope(snapshot:M2AnalysisSnapshot|null, startedAt:string):AgentRunEnvelope<MacroAgentOutput>{return{runId:`macro-${startedAt}`,agent:'macro',agentVersion:'m3a-v1',promptVersion:'macro-agent-v1',status:'UNKNOWN',inputAsOfTime:snapshot?.asOfTime??null,startedAt,finishedAt:now(),output:null,errors:[{code:'AGENT_INPUT_INVALID',message:'M2 snapshot, macro composite, asOfTime, and config versions are required.',retryable:false}]};}
export async function runMacroAgent(snapshot:M2AnalysisSnapshot|null, llm:StructuredLlmClient):Promise<AgentRunEnvelope<MacroAgentOutput>> { const startedAt=now(); if(!snapshot||!snapshot.composites?.macro||!snapshot.asOfTime||!snapshot.configVersions?.length)return unknownEnvelope(snapshot,startedAt); const context=contextOf(snapshot); try { const output=await llm.generateStructured<MacroAgentOutput>({systemPrompt:macroSystemPrompt,inputPrompt:macroInputPrompt(context),context}); const err=validateMacroOutput(output,new Set(context.evidence.map(x=>x.id))); if(err)return{runId:`macro-${startedAt}`,agent:'macro',agentVersion:'m3a-v1',promptVersion:'macro-agent-v1',status:'FAILED',inputAsOfTime:snapshot.asOfTime,startedAt,finishedAt:now(),output:null,errors:[err]}; if(JSON.stringify(output.sourceSnapshot)!==JSON.stringify(context.sourceSnapshot))return{runId:`macro-${startedAt}`,agent:'macro',agentVersion:'m3a-v1',promptVersion:'macro-agent-v1',status:'FAILED',inputAsOfTime:snapshot.asOfTime,startedAt,finishedAt:now(),output:null,errors:[{code:'AGENT_OUTPUT_INVALID',message:'Source snapshot was modified.',retryable:false}]}; return{runId:`macro-${startedAt}`,agent:'macro',agentVersion:'m3a-v1',promptVersion:'macro-agent-v1',status:output.status==='UNKNOWN'?'UNKNOWN':'COMPLETED',inputAsOfTime:snapshot.asOfTime,startedAt,finishedAt:now(),output,errors:[]}; } catch { return{runId:`macro-${startedAt}`,agent:'macro',agentVersion:'m3a-v1',promptVersion:'macro-agent-v1',status:'FAILED',inputAsOfTime:snapshot.asOfTime,startedAt,finishedAt:now(),output:null,errors:[{code:'LLM_ERROR',message:'Structured LLM client failed.',retryable:true}]}; } }
